### ISSUE TITLE
Conflict with laravel 5.2 , how to solve it ?

### ISSUE THREAD

**Issue by Fermekoo** [mtownsend5512/request-xml#1]

**Comment by markdieselcore** [comment]
You have two options:

The first is to upgrade your Laravel application. [Laravel Shift](https://laravelshift.com/) provides an excellent service to do this for very low cost. You can also perform the upgrade yourself using Laravel's [upgrade guide](https://laravel.com/docs/5.2/upgrade).

Alternatively, you can fork this repository, change the composer.json and lower the requirements for these components to a satisfactory version. Though I can't guarantee you won't run into issues doing this.

```json
"illuminate/support": "^5.3",
"illuminate/http": "^5.2",
```

Overall, my recommendation is to upgrade your Laravel application. You're bound to run into this issue more and more with other packages.
