### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by tumainimosha** [mtownsend5512/request-xml#3]

**Comment by singhsanjay5151** [comment]
Is it supporting PHP 8.0 ???

i am getting following error with php 8.0 and lumen version 8 ---

 [InvalidArgumentException]
 Package mtownsend/request-xml has a PHP requirement incompatible with your
 PHP version, PHP extensions and Composer version


equire [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-su
gest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-
ev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with
dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-
EQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packag
s] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader]
[--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by tm1000** [comment]
~~Solved in https://github.com/mtownsend5512/request-xml/commit/f30cc6b9a471aa63a9ad5a3bc1d58d5953873d0c~~

**Comment by Cluster2a** [comment]
> Solved in [f30cc6b](https://github.com/mtownsend5512/request-xml/commit/f30cc6b9a471aa63a9ad5a3bc1d58d5953873d0c)

@mtownsend5512, @tm1000, this does not seems to work properly:
![image](https://user-images.githubusercontent.com/84905165/120907794-c63f5280-c664-11eb-9d08-cff297498640.png)
![image](https://user-images.githubusercontent.com/84905165/120907797-cf302400-c664-11eb-940c-5885d6a92ad4.png)

After removing ```"mtownsend/xml-to-array": "^2.0",``` it stills throws an error:
 
![image](https://user-images.githubusercontent.com/84905165/120907804-ec64f280-c664-11eb-90ba-a7da5afbc3a1.png)
![image](https://user-images.githubusercontent.com/84905165/120907813-fbe43b80-c664-11eb-8b2a-e0df37faf720.png)

Do you have any idea?

**Comment by tm1000** [comment]
@Cluster2a see #5

**Comment by Cluster2a** [comment]
> @Cluster2a see #5

thanks :+1:

**Comment by tm1000** [comment]
I was hoping @mtownsend5512 would have merged this by now he might be out of the office. I will try to reach him on Twitter

**Comment by mtownsend5512** [comment]
Hi, I've been very busy. I will look at this on Monday morning. Thanks for your patience and help!

**Comment by tm1000** [comment]
@mtownsend5512 would you be able to merge this and issue a release?

**Comment by mtownsend5512** [comment]
2.1.0 now supports PHP 8 thanks to PR #5
