### ISSUE TITLE
Installation Error with php version 8.0 and lumen 8

### ISSUE THREAD

**Issue by singhsanjay5151** [mtownsend5512/request-xml#4]
Is it supporting PHP 8.0 ???

i am getting following error with php 8.0 and lumen version 8 ---

[InvalidArgumentException]
Package mtownsend/request-xml has a PHP requirement incompatible with your
PHP version, PHP extensions and Composer version

equire [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-su
gest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-
ev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with
dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-
EQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packag
s] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader]
[--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] []...

**Comment by tm1000** [comment]
Solved in https://github.com/mtownsend5512/request-xml/commit/f30cc6b9a471aa63a9ad5a3bc1d58d5953873d0c

**Comment by tm1000** [comment]
See #3
